### ISSUE TITLE
Add .pt3 support

### ISSUE THREAD

**Issue by talaurence** [Photon-HDF5/phconvert#13]
I need to add .pt3 support.

**Comment by talaurence** [comment]
First attempt: write the PT3 support by modifying the functions to decode HT3.

**Comment by tritemio** [comment]
Great! For reference, more info on adding a new picoquant file in #12.

**Comment by talaurence** [comment]
I need a little help getting started with Git.  I have never actually used the source code control.  Everything is installed, but I have no clue where I get and how I edit the source code.  Essentially, I want to edit your pqreader module to create functions just like your  ht3_reader() and ht3_process() (on my system, it seems to appear as process_t3records().  Are those the same?

What do I do with Git in order to get the source code?  Where do I edit it?  Do I use Spyder and run it using the IPython console like normal, or is there some other mechanism?

Thanks,

Ted

**Comment by tritemio** [comment]
I found a GitHub help page that explain the same thing:
https://help.github.com/articles/fork-a-repo/

**Comment by tritemio** [comment]
I pasted the above guide to the phconvert wiki: https://github.com/Photon-HDF5/phconvert/wiki/How-to-contribute-on-Github

**Comment by tritemio** [comment]
This issue is closed by #14
