### ISSUE TITLE
multispot TCSPC data file

### ISSUE THREAD

**Issue by smXplorer** [Photon-HDF5/phconvert#15]
Multispot TCSPC files currently have a detectors field, even tough there is only one detector per spot.
Moreover there is no detector_specs field, so routines designed to interpret the former using the latter fail.

**Comment by smXplorer** [comment]
Additionally, the laser_repetition_rate is missing in those files (in the comment above, I should have said that not only is there no detector_specs group, but there is no measurement_specs group either. laser_repetition_rate should be part of that group.

**Comment by tritemio** [comment]
We will define a smFRET_TCSPC measurement type for Photon-HDF5 v0.5 that will include all of these. Closing here, discussion will be in there: https://github.com/Photon-HDF5/photon-hdf5/issues/34.
