### ISSUE TITLE
Documentation & Information for process_t3records function

### ISSUE THREAD

**Issue by ncodina** [Photon-HDF5/phconvert#19]
Hello, we are trying to use the `process_t3records` function from phconvert:

http://phconvert.readthedocs.io/en/latest/pqreader.html#phconvert.pqreader.process_t3records

We can see that this function returns three arrays: detectors, timestamps, and nanotimes. Is there more documentation for these 3 arrays? Specifically we are currently struggling to understand the values in the `detectors` array.

So far we haven't been able to find documentation from picoquant's demo code either.

**Comment by tritemio** [comment]
Yeah, that function didn't have much documentation. I added some:

http://phconvert.readthedocs.io/en/latest/pqreader.html#phconvert.pqreader.process_t3records

Hopefully this is clear, otherwise feel free to ask or suggest improvements.

**Comment by tritemio** [comment]
Closing. Feel free to open a new issue if you have further questions.
