### ISSUE TITLE
Save to Photon-HDF5 files 'smFRET' measurement

### ISSUE THREAD

**Issue by ncodina** [Photon-HDF5/phconvert#20]
Hi,
We just decoded a .PTU file and have the arrays of: timestamps, detectors and nanotimes. We want to save it to Photon-HDF5. The type of measurement is a single laser excitation. We have questions about some of the parameters:

1. How to know the list of donor and acceptor's IDs?
```python
measurement_specs = dict(
    measurement_type = 'smFRET',
    detectors_specs = {'spectral_ch1': [0],  # list of donor's detector IDs
                       'spectral_ch2': [1]})  # list of acceptor's detector IDs
```

2. Where do we obtain the values for `timestamps_unit`, `tcspc_unit`, and `tcspc_num_bins`?
```python
photon_data = dict(
    timestamps=timestamps,
    detectors=detectors,
    timestamps_specs={'timestamps_unit': timestamps_unit},
    nanotimes=nanotimes,
    nanotimes_specs={'tcspc_unit': tcspc_unit,'tcspc_num_bins': tcspc_num_bins,'tcspc_range': tcspc_range},
    measurement_specs = measurement_specs)
```

3. Just to check if the group setup settings have been selected correctly for the type of measurement.
```python
setup = dict(
    num_pixels = 2,               # using 2 detectors
    num_spots = 1,                # a single confocal excitation
    num_spectral_ch = 2,          # donor and acceptor detection 
    num_polarization_ch = 1,      # number of detected polarization states 
    num_split_ch = 1,             # no beam splitter
    modulated_excitation = False, # CW excitation, no modulation - True if excitation is alternated
    lifetime = True)             # no TCSPC in detection
```

**Comment by tritemio** [comment]
1. You should know which detector is donor/acceptor from the physical connection. Otherwise you can simply guess (if it's hard use a D-only sample)

2. The values timestamps_unit, tcspc_unit, and tcspc_num_bins should be extracted from the file header. See the "table" of fields contained in the header printed in the example notebook:

https://gist.github.com/tritemio/734347586bc999f39f9ffe0ac5ba0e66

3. Look OK.

**Comment by ncodina** [comment]
Thanks very much!

We have some further question in point 2:
`timestamps_unit` is specified in "MeasDesc_GlobalResolution" in the header
`tcspc_unit` is specified in "MeasDesc_Resolution" in the header
`tcspc_range` = tcspc_unit * tcspc_num_bins
And how do we get `tcspc_num_bins`? What is the relationship with "MeasDesc_BinningFactor"?

We have seen written tcspc_unit and nanotimes_unit to represent the same. What is the difference and how do we know which one to use?

**Comment by tritemio** [comment]
I don't know :). I suppose most or all TCSPC hardware from PicoQuant has 4096 TCSPC bins?

For "MeasDesc_BinningFactor", I don't know either, I don't have any secret info on the file format I'm just guessing by looking at the demo code :). If I have to guess you multiply "HW_BaseResolution" by "MeasDesc_BinningFactor" to obtain "MeasDesc_Resolution". But the definitive answer can only come from PicoQuant. They should provide documentation of their PTU format, especially to a customer.

**Comment by tritemio** [comment]
Regarding `tcspc_unit` and `nanotimes_unit` it is the same thing. In Photon-HDF5 it is always called `tcspc_unit`. In the phconvert code the variable is called `nanotimes_unit` for historical reasons. I think the field in the format was changed during early development because we thought that 'tcspc' was a more broadly understood term than `nanotime`.

**Comment by snizzleorg** [comment]
@tritemio different harps have different numbers of bins. Hydraharp has 65536 bins.

**Comment by snizzleorg** [comment]
@tritemio Hydraharp has 65536 bins in tttr modes. Basically this is limited by the 16bit width of the bin number.

**Comment by tritemio** [comment]
@snizzleorg, thanks. Is the number of bins available in the PTU header?

**Comment by snizzleorg** [comment]
@tritemio 
It is not in the header 
Different TCSPC units have different *maximum* bin numbers.

HH400:
https://github.com/PicoQuant/HH400-v3.x-Demos/blob/master/Windows/64bit/c/tttrmode/hhdefin.h#L18

TH260:
https://github.com/PicoQuant/TH260-Demos/blob/master/Windows/64%20bit/C/tttrmode/th260defin.h#L28

PH300:
https://github.com/PicoQuant/PH300-v3.x-Demos/blob/master/Windows/64/c/TTTRmode/phdefin.h#L11

The actual number of bins used however will depend on the reputation rate and the bin width used.
it is defined by the timing resolution and the time window between the two SYNC pulses.
For a measurement

- 20MHz repetition rate  - > time between pulses 50 ns
-  8 ps resolution
Number of time bins: 6250 

What is given in the header is tag is the  
```<Hardware Header>```
```HW_BaseResolution```  !!!THIS IS THE LOWEST RESOLUTION POSSIBLE!!!
and under tag
```<TT Measurement Results>```
```MeasDesc_Resolution```  !!!!THIS IS THE RESOLUTION YOU USED FOR THE MEASUREMENT!!!
further, under tag
```<TT Measurement Results>```
you'll find
```TTResult_SyncRate```

**Comment by ncodina** [comment]
Hi,
Yes this is correct. Thanks very much @snizzleorg. 
Just to confirm I received this answer from PicoQuant: 

"There is no info about this in the header.
This number is defined by the timing resolution and the time window between the two SYNC pulses.
For a measurement 
20MHz repetition rate  - > time between pulses 50 ns
and 8 ps resolution 
Number of time bins: 6250 "

**Comment by tritemio** [comment]
@snizzleorg, @ncodina thanks for the info! This is a good reference.

We can just compute the number of bins for any PTU file using these tags from the header:

```
(1 / TTResult_SyncRate) / MeasDesc_Resolution
```

Do you agree this will work for all PicoQuant hardware and configurations?

**Comment by ncodina** [comment]
Just to confirm, in my case "smFRET" then, `tcspc_range` = `timestamps_unit`
Is that correct?

`timestamps_unit`: "MeasDesc_GlobalResolution"
`tcspc_unit`: "MeasDesc_Resolution"
`tcspc_num_bins`: "MeasDesc_GlobalResolution" / "MeasDesc_Resolution" = timestamps_unit / tcspc_unit ?
`tcspc_range` = tcspc_unit * tcspc_num_bins = `timestamps_unit` ?

**Comment by smXplorer** [comment]
I fear there is some confusion brewing up here...
There are typically two distinct "clock units"  in a TCSPC measurement.
1) The TAC or TDC resolution (which apparently PQ now splits into the hardware native resolution and the user-selected measurement resolution). This is in the sub-ns range in general (it depends on the TAC/TDC measurement range, which is typically adjustable). That apparently is called MeasDesc_Resolution in those files. This is what is called tcspc_unit in Photon-HDF5.

2) the photon macrotime unit, typically provided by a clock on the board, not necessarily related to the hardware used for time-to-laser measurements. This is typically 50 ns or something of this order. This corresponds to timestamps_unit in Photon-HDF5 and seem to correspond to MeasDesc_GlobalResolution (from what you are describing).

This (And what follows) is wrong: tcspc_num_bins: "MeasDesc_GlobalResolution" / "MeasDesc_Resolution"
The number of TCSPC bin can probably be obtained safely as described above: 

tcspc_num_bins = (1 / TTResult_SyncRate) / MeasDesc_Resolution

The TCSPC range is obviously:

tcspc_range = 1 / TTResult_SyncRate (= tcspc_unit * tcspc_num_bins)

**Comment by ncodina** [comment]
In my files MeasDesc_GlobalResolution = (1 / TTResult_SyncRate)

when repetition rate is 20 MHz:
MeasDesc_GlobalResolution = 5e-08
TTResult_SyncRate = 20000000

when repetition rate is 40 MHz:
MeasDesc_GlobalResolution = 2.5e-08
TTResult_SyncRate = 40000080

is it not always the case? is `tcspc_unit` related to the time window between the two SYNC pulses?

**Comment by smXplorer** [comment]
OK, so for this PQ hardware, the macrotime clock IS linked to the TCSPC hardware in the sense that they use the laser sync as a clock for photon time stamps... Kind of flaky if the laser is not stable, but probably good enough for usual measurement durations.
Just for info (if you happen to ever read other Photon-HDF5 files) this is not the rule (i.e. the timestamps_unit might not have anything to do with a laser rep rate - think CW lasers).

**Comment by tritemio** [comment]
@ncodina, `tcspc_unit` in the bin-width on the TCSPC histogram or in other words the units of the nanotimes array (nanotimes are integer, an increment of 1 in nanotimes = tcspc_unit in seconds).

**Comment by ncodina** [comment]
Ah thanks very much for letting me know :).

I didn't know why did we had to specify tcspc_num_bins if it could be calculated from timestamps_unit and tcspc_unit. But I see that this is my case, and in some situations timestamps_unit will not be related to the laser repetition rate.

**Comment by tritemio** [comment]
@ncodina, thanks for reporting this. I replied  in the other issue #12 since this is a bug in the PTU decoder.

**Comment by tritemio** [comment]
The discussion here seems to be solved. closing it.
