### ISSUE TITLE
Detector pixel spatial position

### ISSUE THREAD

**Issue by jrivers96** [Photon-HDF5/phconvert#28]
How do you retrieve the 2D spatial positions for the detector pixels?

http://photon-hdf5.readthedocs.io/en/latest/phdata.html#detector-pixel-ids

I'm currently getting a 1 dim array back. 

``
>>> np.unique(detectors)
array([  0,  65,  66,  68, 127], dtype=uint8)
>>> np.sum(detectors == 65)
2570
>>> np.sum(detectors == 66)
2570
>>> np.sum(detectors == 68)
10
>>> np.sum(detectors == 127)
1809294
>>> np.sum(detectors == 0)
12185306
``

**Comment by tritemio** [comment]
Hi @jrivers96, the [new version 0.5](https://photon-hdf5.readthedocs.io/en/0.5.dev/whats_new_ver05.html) has an array called `/setup/detectors/positions` which contains the (x, y) position of each pixel, in the same order as the detectors IDs:

https://photon-hdf5.readthedocs.io/en/0.5.dev/phdata.html#detectors-group

The logic is the following, `/photon_dataN/detectors` contains detector IDs (a number for each detector). The in `/setup/detectors/` you find the mapping between IDs and spatial position and other pixel info. For example: DCR, name of the module (for multiple arrays), afterpulsing, etc..

**Comment by jrivers96** [comment]
Is there a recommended loading approach for a "ptu" file?

I'm currently just doing:

`timestamps, detectors, nanotimes, meta = phconvert.phconvert.pqreader.load_ptu(filename)`

**Comment by tritemio** [comment]
@jrivers96, please open a new issue for different questions. PTU decoding should work for the following variants rtPicoHarpT3, rtHydraHarp2T3, rtTimeHarp260NT3, rtTimeHarp260PT3. Please make sure you use the latest phconvert version (0.8.2 as of writing).

**Comment by tritemio** [comment]
@jrivers96, would also be nice if you reply to my first answer to tell is it addresses your initial question.

**Comment by jrivers96** [comment]
Thanks for the response. Your first answer did answer my question.
