### ISSUE TITLE
Decoding spatial features of HydraHarpT3V2 data

### ISSUE THREAD

**Issue by jrivers96** [Photon-HDF5/phconvert#29]
I can't seem to get spatial features from the detections, only a 1D array. The meta data clearly shows a 256 x 256 x 10 array with 1560 time points per pixel. 

![image](https://user-images.githubusercontent.com/11034356/41932175-43857f88-794e-11e8-907e-caa46a6b8695.png)

The below shows a pprint on some of the meta fields showing spatial dimensions for the data. 

![image](https://user-images.githubusercontent.com/11034356/41932420-f0724960-794e-11e8-88cb-a77ab05b64fa.png)

**Comment by jrivers96** [comment]
FYI @apoliakov

**Comment by tritemio** [comment]
`load_ptu` returns 3 arrays (timestamps, detectors, nanotimes) and a dictionary (`meta`). In `meta` you find a few items such as measurement duration, but for the most part it is just a direct mapping of the header data. If the header contains the information you need, you should be able to extract it from `meta['tags']`.

That said, you have only 5 detectors IDs. I'm guessing this some kind of scanning confocal data? In this case you probably have markers in your arrays to mark the line, and frame end. We currently have no support for reconstructing images or volumes from this data. You need to do it manually from the arrays.

**Comment by snizzleorg** [comment]
Please check the principles of TCSPC available for example here: https://www.picoquant.com/images/uploads/page/files/7253/technote_tcspc.pdf (specifically page 12). As @tritemio pointed out, the markers coming from your scanner are interlaced with the photons and are needed for reconstructing the image out of your photo data stream.
