### ISSUE TITLE
Converting ptu-file

### ISSUE THREAD

**Issue by nzijlstra** [Photon-HDF5/phconvert#30]
I am trying to convert Picoquant ptu files. We have a setup with a hydraharp400, PIE excitation, 2 color detection, and 2 polarizations. To do this, I'm opening the file using the pq_reader and use a generic measurement type to create the photon-hdf5 file.
If I now use the following setup configuration

```
setup = dict(
    num_pixels = 4,                   # using 4 detectors
    num_spots = 1,                    # a single confocal excitation
    num_spectral_ch = 2,              # donor and acceptor detection 
    num_polarization_ch = 2,          # two polarizations
    num_split_ch = 1,                 # no additional beam splitter
    modulated_excitation = True,     # PIE
    excitation_alternated = [True,True],  
    lifetime = True,                 #  TCSPC in detection
    laser_repetition_rates=[40e6,40e6],
    
    ## Optional fields
    excitation_wavelengths = [532e-9,635e-9],         # List of excitation wavelenghts
    excitation_cw = [False,False],                    # List of booleans, True if wavelength is CW
    detection_wavelengths = [580e-9, 640e-9], 
)

```
and measurement_spec:

```
measurement_specs = dict(
    measurement_type = 'generic',
    detectors_specs = {
          'polarization_ch1':[2,0],
          'polarization_ch2':[3,1],
        'spectral_ch1':[2,3],
        'spectral_ch2':[0,1],
    },
    laser_repetition_rate=40e6,
    alex_excitation_period1=[1550,3125],
    alex_excitation_period2=[0,1500]
    )
```
I can create/save an photon-hdf5 file without issue, but when I try to load it (using fretbursts.loader.photon_hdf5), I get the error that the polarization_ch* is missing in detectors_specs.
If I simplify the setup to 2 spectral channels and no polarization, it al seems to work fine and I can open it. Is there something wrong with my setup or am I supposed to specify more?

Additionally, the length of the measurement of the file loaded using pq_reader, is not the same length as my original recording. Any ideas about what is going on here, is this a known issue?
All input is more than welcome! Thanks a lot!

**Comment by tritemio** [comment]
You are probably seeing a bug in FRETBursts which prevented loading files with polarization. See https://github.com/OpenSMFS/FRETBursts/issues/18.

The bug was recently fixed in https://github.com/OpenSMFS/FRETBursts/pull/19. To get the fix you should use the FRETbursts from the master branch on github untill the next release.

**Comment by nzijlstra** [comment]
Great, this solved the issue with loading the file!
But when I look at the length of my time trace after loading, it still is much shorter than the recording time (recording 1800s, trace length 1473.95s).
Any ideas on where this might come from?

**Comment by tritemio** [comment]
@nzijlstra, thanks for reporting back and glad that the first issue is solved. Since this seems an issue with FRETBurst I ask if you can open an issue on:

https://github.com/OpenSMFS/FRETBursts/issues

Please report the output of 

```
d.time_min, d.time_max, d.clk_p
```

before and after applying alternation.

Thanks, I'm closing the issue here.
