### ISSUE TITLE
Workaround empty string h5labview bug

### ISSUE THREAD

**Issue by tritemio** [Photon-HDF5/phconvert#4]
Empty strings in `TITLE` cause LabVIEW (h5labview) to crash. 

Pytables puts, by default, an empty string in `TITLE` when no description is provided. This happens in Photon-HDF5 files with user fields without a description.

A workaround is saving a single space when there is no description.

**Comment by smXplorer** [comment]
The workaround in 0.5.7 works with h5labview 2.11.12 (tested with LabVIEW 2013 SP1 64 bit)
