### ISSUE TITLE
Sample PHU file

### ISSUE THREAD

**Issue by tritemio** [Photon-HDF5/phconvert#40]
We need a test PHU file for testing the new `load_phu` function introduced by #37.

@seb5g, can you please provide a sample PHU file to add to the test suite?

**Comment by seb5g** [comment]
Here you go:
https://drive.google.com/file/d/1nT1WAOPDQF8LxsMc3QNVJSi76F4RW02_/view?usp=sharing

Sébastien Weber
*Président AbsoluRaid*
*seba.weber@gmail.com <seba.weber@gmail.com>*

*www.absoluraid.com <http://www.absoluraid.com>*
