### ISSUE TITLE
bh_print_sys_params() fails on python

### ISSUE THREAD

**Issue by dmopalmer** [Photon-HDF5/phconvert#45]
`bh_print_sys_params()` in bhreader.py calls `dict.iteritems()` which is no longer in python3.

Since the dict in question is small, there is no reason not to use `dict.items()` instead.

This is true whether installed with `conda -c conda-forge` (v0.9) or `pip` (still v0.8.2 on pypi).

**Comment by tritemio** [comment]
Thanks for the report. Would you mind sending a PR?

PS: dict.items() in python 3 is a generator like it was dict.iteritems() in python 2, so it is efficient.

**Comment by dmopalmer** [comment]
The pull request #46 includes other features that it showed were necessary.

**Comment by tritemio** [comment]
@dmopalmer, thanks for your contribution! It would be nice to also have a test to avoid these errors in the future. 

Would you mind adding one to test_bhreader.py? 
(the test there use the nose format, but you can use the simpler pytest format as in test_pqreader.py)
