### ISSUE TITLE
Save scalar values as scalar

### ISSUE THREAD

**Issue by tritemio** [Photon-HDF5/phconvert#5]
Currently arrays of size == 1 are allowed in scalar fields. This cause problems when reading in strongly typed languages.

For consistency is better to always save scalars as scalars.

**Comment by smXplorer** [comment]
It is indeed.

**Comment by tritemio** [comment]
Solved in version 0.6 (https://github.com/Photon-HDF5/phconvert/releases/tag/0.6).
