### ISSUE TITLE
PyPi version is outdated

### ISSUE THREAD

**Issue by klockeph** [Photon-HDF5/phconvert#50]
Hi,

the version on PyPi is on 0.8.2 and missing the fix for #48

Could you upload the new release to PyPi aswell?

Thanks

**Comment by klockeph** [comment]
(in the meantime you can use ```pip install git+https://github.com/Photon-HDF5/phconvert``` in case you need this)

**Comment by harripd** [comment]
I have taken over managing phconvert and am now keeping conda and pypi synced.
