### ISSUE TITLE
what are the photons in detector 127?

### ISSUE THREAD

**Issue by Mattyboi123** [Photon-HDF5/phconvert#51]
Hello,

I am using phconvert for nsALEX, in the example script where a ptu file is converted to hdf5, the detector containing the greatest number of photons is not used...what does this mean? what are these photons and why is it reasonable to omit them from analysis?

**Comment by mayeshh** [comment]
@tritemio no longer maintains this repo, so I will attempt to answer your question. 

The [notebook](https://github.com/Photon-HDF5/phconvert/blob/master/notebooks/Convert%20PicoQuant%20ns-ALEX%20files%20to%20Photon-HDF5.ipynb) you are referencing provides an example of how to filter photons from the data object `d`. The reason provided is simply "to save space". If you do not need to save space, there is no need to filter your photons in this manner. However, there are reasons that you might want to filter your photon data, e.g. if you have a detector that has a high dark count rate you may choose to remove it from the analysis.

**Comment by jacrossley** [comment]
I believe in picoquant .ptu files channel 127 is the overflow channel? (more info on overflows here: https://www.picoquant.com/images/uploads/page/files/14528/technote_tttr.pdf). Not an issue with phconvert though, so we can probably close the issue.
